### ISSUE TITLE
Updates check fails due to the missing uithemes plugin

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/plugin-installation-manager-tool#101]
UI Themes plugin is hidden in the update center, and not mentioned in the dependency tree, but the  https://github.com/jenkins-infra/update-center2/blob/434567c532f60c87d6d056e04b3884daf42deb0e/resources/artifact-ignores.properties#L139

## Steps to reproduce

1. Check out https://github.com/oleg-nenashev/demo-jenkins-config-as-code
2. Run `make show-updates`. It will invoke `	java -jar tmp/jenkins-plugin-manager.jar --list -f plugins.txt --no-download -d tmp/plugins -w tmp/jenkins.war --available-updates
`

## Diagnostics info

```
Available updates:
github-branch-source (2.7.1) has an available update: 2.8.0
snakeyaml-api (1.26.1) has an available update: 1.26.4
pipeline-stage-tags-metadata (1.6.0) has an available update: 1.7.0
manage-permission (1.0) has an available update: 1.0.1
pipeline-model-definition (1.6.0) has an available update: 1.7.0
data-tables-api (1.10.20-14) has an available update: 1.10.21-1
github-api (1.111) has an available update: 1.112.0
echarts-api (4.6.0-8) has an available update: 4.7.0-4
Unable to find plugin uithemes in update center https://updates.jenkins.io/update-center.actual.json
```

Plugins.txt

```
ace-editor:1.1
authorize-project:1.3.0
blueocean:1.23.2
cloud-stats:0.25
cloudbees-folder:6.12
cobertura:1.16
code-coverage-api:1.1.6
configuration-as-code:1.41
docker-commons:1.16
docker-workflow:1.23
email-ext:2.69
extended-read-permission:3.2
favorite:2.3.2
filesystem_scm:2.1
git-client:3.2.1
git:4.2.2
github-api:1.111
github-branch-source:2.7.1
github:1.30.0
jackson2-api:2.11.0
jacoco:3.0.4
javadoc:1.5
jdk-tool:1.4
job-restrictions:0.8
jsch:0.1.55.2
junit:1.27
locale:1.4
lockable-resources:2.8
mailer:1.32
manage-permission:1.0
matrix-auth:2.6.1
maven-plugin:3.6
momentjs:1.1.1
monitoring:1.83.0
ownership:0.12.1
parallel-test-executor:1.12
parameterized-trigger:2.36
pipeline-build-step:2.12
pipeline-model-definition:1.6.0
pipeline-stage-tags-metadata:1.6.0
pipeline-stage-view:2.13
role-strategy:2.16
run-condition:1.3
scm-api:2.6.3
security-inspector:0.5
ssh-credentials:1.18.1
timestamper:1.11.3
token-macro:2.12
warnings-ng:8.1.0
workflow-basic-steps:2.20
workflow-cps:2.80
workflow-durable-task-step:2.35
workflow-job:2.39
workflow-multibranch:2.21
workflow-scm-step:2.11
yet-another-docker-plugin:0.2.0
```

**Comment by oleg-nenashev** [comment]
Trace of the verbose output:

```
yet-another-docker-plugin depends on: 
icon-shim 1.0.5
cloud-stats 0.23
credentials 2.1.3
docker-commons 1.3.1
durable-task 1.3
ssh-slaves 1.22

icon-shim depends on: 
uithemes 1.0
```

```
Resolving dependencies of uithemes by downloading plugin to temp file /tmp/uithemes1975477877833751029.jpi and parsing MANIFEST.MF

uithemes has no dependencies
```

```
onenashev@LAPTOP-25K65LOS:/c/Users/Oleg/Documents/jenkins/demo/demo-jenkins-config-as-code$ make show-updates > log.txt
io.jenkins.tools.pluginmanager.impl.PluginNotFoundException: Unable to find plugin uithemes in update center https://updates.jenkins.io/update-center.actual.json
        at io.jenkins.tools.pluginmanager.impl.PluginManager.getLatestPluginVersion(PluginManager.java:562)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.showAvailableUpdates(PluginManager.java:329)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:131)
        at io.jenkins.tools.pluginmanager.cli.Main.main(Main.java:37)
Unable to find plugin uithemes in update center https://updates.jenkins.io/update-center.actual.json
make: *** [show-updates] Error 1
```

Looks like I should  either migrate out of Yet Another Docker plugin or to force an explicit version if icon-shim in the plugins.txt

**Comment by oleg-nenashev** [comment]
Update did not work, because the same happens for the Docker commons plugin according to the tool.

```
docker-commons depends on:
authentication-tokens 1.1
icon-shim 1.0.3
credentials 1.22
```

It is odd taking pom.xml for that version: https://github.com/jenkinsci/docker-commons-plugin/blob/docker-commons-1.16/pom.xml#L58-L73. Will debug the tool

**Comment by oleg-nenashev** [comment]
Note: The run still fails on the master branch even if the `--skip-failed-plugins ` flag is set

**Comment by oleg-nenashev** [comment]
Funny thing about the implementation. It will recursively check dependencies even if another version is specified in plugins.txt BEFORE the plugin.

```
icon-shim:2.0.3
yet-another-docker-plugin:0.2.0
```

Leads to....

```
icon-shim has no dependencies

yet-another-docker-plugin depends on: 
icon-shim 1.0.5
cloud-stats 0.23
credentials 2.1.3
docker-commons 1.3.1
durable-task 1.3
ssh-slaves 1.22

icon-shim depends on: 
uithemes 1.0
```
