### ISSUE TITLE
Error installing latest versions of pipeline-model-definition and workflow-multibranch at the same time

### ISSUE THREAD

**Issue by sebthom** [jenkinsci/plugin-installation-manager-tool#176]
When trying to install these two plugins via the jenkins-plugin-manager:
```
pipeline-model-definition:latest
workflow-multibranch:latest
```
the following error is thrown:
```
Plugin pipeline-model-definition:1.7.1 depends on workflow-multibranch:2.22, 
but there is an older version defined on the top level - workflow-multibranch:latest
```

**Comment by halkeye** [comment]
More sample data:

Plugin basic-branch-build-strategies:1.3.2 depends on cloudbees-folder:6.14, but there is an older version defined on the top level - cloudbees-folder:latest

https://github.com/halkeye-docker/docker-jenkins/blob/27ffaa459d9b71e911cab0bcdea2b3c2b14ae5c4/plugins.txt

```
bash-5.0$ java -jar /usr/lib/jenkins-plugin-manager.jar  --war /usr/share/jenkins/jenkins.war  --plugin-file /usr/share/jenkins/ref/plugins.txt --verbose
File containing list of plugins to be downloaded: /usr/share/jenkins/ref/plugins.txt
Reading in plugins from /usr/share/jenkins/ref/plugins.txt

Invalid URL :https://files.halkeye.net/html5-notifier-plugin.hpi , will ignore
No directory to download plugins entered. Will use default of /usr/share/jenkins/ref/plugins
Using update center https://updates.jenkins.io/update-center.json from JENKINS_UC environment variable
Using experimental update center https://updates.jenkins.io/experimental/update-center.json from JENKINS_UC_EXPERIMENTAL environment variable
Using incrementals mirror https://repo.jenkins-ci.org/incrementals from JENKINS_INCREMENTALS_REPO_MIRROR environment variable
No CLI option or environment variable set for plugin info, using default of https://updates.jenkins.io/plugin-versions.json
Will use war file: /usr/share/jenkins/jenkins.war
Jenkins version: 2.256

Retrieving update center information
Returning cached value for: update-center-2.256
Returning cached value for: experimental-update-center-2.256
Returning cached value for: plugin-versions

ansicolor has no dependencies

authorize-project has no dependencies

badge depends on:
workflow-step-api 2.22
antisamy-markup-formatter 2.1
script-security 1.74
structs 1.20

workflow-step-api depends on:
structs 1.20

antisamy-markup-formatter has no dependencies

script-security has no dependencies

structs has no dependencies

basic-branch-build-strategies depends on:
branch-api 2.6.0
scm-api 2.6.3
structs 1.20

branch-api depends on:
cloudbees-folder 6.14
scm-api 2.6.3
io.jenkins.tools.pluginmanager.impl.PluginDependencyStrategyException: Plugin basic-branch-build-strategies:1.3.2 depends on cloudbees-folder:6.14, but there is an older version defined on the top level - cloudbees-folder:latest
        at io.jenkins.tools.pluginmanager.impl.PluginManager.resolveRecursiveDependencies(PluginManager.java:843)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.findPluginsAndDependencies(PluginManager.java:484)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:147)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:112)
        at io.jenkins.tools.pluginmanager.cli.Main.main(Main.java:63)
Plugin basic-branch-build-strategies:1.3.2 depends on cloudbees-folder:6.14, but there is an older version defined on the top level - cloudbees-folder:latest
```

**Comment by timja** [comment]
PR https://github.com/jenkinsci/plugin-installation-manager-tool/pull/184
