### ISSUE TITLE
Plugins cannot be downloaded when some sites are blocked but not others

### ISSUE THREAD

**Issue by jyaworski** [jenkinsci/plugin-installation-manager-tool#177]
Hello:

Sometime around August 19th, our jenkins builds using version 2.0.0 stopped working. Upon further investigation, it appears that jenkins.io may have changed their behavior:

```
$ curl -I https://updates.jenkins.io/download/plugins/authentication-tokens/1.4/authentication-tokens.hpi
HTTP/1.1 302 Found
Date: Fri, 28 Aug 2020 20:30:53 GMT
Server: Apache/2.4.29 (Ubuntu)
Location: https://get.jenkins.io/plugins/authentication-tokens/1.4/authentication-tokens.hpi
Content-Type: text/html; charset=iso-8859-1

$ curl -I https://get.jenkins.io/plugins/authentication-tokens/1.4/authentication-tokens.hpi
HTTP/1.1 302 Found
Server: nginx/1.19.1
Date: Fri, 28 Aug 2020 20:31:03 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Cache-Control: private, no-cache
Link: <https://ftp.yz.yamagata-u.ac.jp/pub/misc/jenkins/plugins/authentication-tokens/1.4/authentication-tokens.hpi>; rel=duplicate; pri=1; geo=jp
Link: <https://ftp-nyc.osuosl.org/pub/jenkins/plugins/authentication-tokens/1.4/authentication-tokens.hpi>; rel=duplicate; pri=2; geo=us
Link: <https://mirror.xmission.com/jenkins/plugins/authentication-tokens/1.4/authentication-tokens.hpi>; rel=duplicate; pri=3; geo=us
Link: <https://mirror.serverion.com/jenkins/plugins/authentication-tokens/1.4/authentication-tokens.hpi>; rel=duplicate; pri=4; geo=de
Location: https://ftp-chi.osuosl.org/pub/jenkins/plugins/authentication-tokens/1.4/authentication-tokens.hpi
Strict-Transport-Security: max-age=15724800; includeSubDomains
```

If any site in `Link` or `Location` is not reachable, the plugin manager might not work with the following message:

```
Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/authentication-tokens/1.4/authentication-tokens.hpi, or download plugin authentication-tokens to file
```

Could the tool be updated such that it only returns this message if all of the links are unreachable? This is especially a problem for those behind proxies that allow only certain domains to be accessed.

Thanks!

**Comment by martinda** [comment]
So I am trying to understand where things fail. I added a [debug code to a local branch](https://github.com/martinda/plugin-installation-manager-tool/tree/debug-issue-177), and I see the following:
```
Unable to download plugin workflow-basic-steps from https://updates.jenkins.io/download/plugins/workflow-basic-steps/2.20/workflow-basic-steps.hpi
Redirect location: https://get.jenkins.io/plugins/workflow-basic-steps/2.20/workflow-basic-steps.hpi
Redirect location: https://ftp-nyc.osuosl.org/pub/jenkins/plugins/workflow-basic-steps/2.20/workflow-basic-steps.hpi
Selected location: https://ftp-nyc.osuosl.org/pub/jenkins/plugins/workflow-basic-steps/2.20/workflow-basic-steps.hpi
Redirect location: https://get.jenkins.io/plugins/workflow-basic-steps/2.20/workflow-basic-steps.hpi
Redirect location: https://mirror.xmission.com/jenkins/plugins/workflow-basic-steps/2.20/workflow-basic-steps.hpi
Selected location: https://mirror.xmission.com/jenkins/plugins/workflow-basic-steps/2.20/workflow-basic-steps.hpi
io.jenkins.tools.pluginmanager.impl.DownloadPluginException: Unable to download workflow-basic-steps
        at io.jenkins.tools.pluginmanager.impl.PluginManager.lambda$null$6(PluginManager.java:453)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Unable to download workflow-basic-steps
```

I looks like it does not attempt `https://get.jenkins.io/plugins/workflow-basic-steps/2.20/workflow-basic-steps.hpi`

**Comment by martinda** [comment]
It looks like [URIUtils.resolve()](https://github.com/apache/httpcomponents-client/blob/4.5.x/httpclient/src/main/java/org/apache/http/client/utils/URIUtils.java#L490-L518) method picks the last redirect.

**Comment by martinda** [comment]
With the plugin manager (with [my logVerbose](https://github.com/jenkinsci/plugin-installation-manager-tool/compare/master...martinda:debug-issue-177) modification so I can see what's happening):
```
Unable to download plugin branch-api from https://updates.jenkins.io/download/plugins/branch-api/2.6.0/branch-api.hpi
Redirect location: https://get.jenkins.io/plugins/branch-api/2.6.0/branch-api.hpi
Redirect location: https://mirror.xmission.com/jenkins/plugins/branch-api/2.6.0/branch-api.hpi
Selected location: https://mirror.xmission.com/jenkins/plugins/branch-api/2.6.0/branch-api.hpi
Redirect location: https://get.jenkins.io/plugins/branch-api/2.6.0/branch-api.hpi
Redirect location: https://ftp-chi.osuosl.org/pub/jenkins/plugins/branch-api/2.6.0/branch-api.hpi
Selected location: https://ftp-chi.osuosl.org/pub/jenkins/plugins/branch-api/2.6.0/branch-api.hpi
Redirect location: https://get.jenkins.io/plugins/branch-api/2.6.0/branch-api.hpi
Redirect location: https://mirror.xmission.com/jenkins/plugins/branch-api/2.6.0/branch-api.hpi
Selected location: https://mirror.xmission.com/jenkins/plugins/branch-api/2.6.0/branch-api.hpi
io.jenkins.tools.pluginmanager.impl.DownloadPluginException: Unable to download branch-api
        at io.jenkins.tools.pluginmanager.impl.PluginManager.lambda$null$6(PluginManager.java:453)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Unable to download branch-api
```

With curl:
```
curl -v -L -X GET https://updates.jenkins.io/download/plugins/branch-api/2.6.0/branch-api.hpi -o branch-api.hpi.2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* About to connect() to updates.jenkins.io port 443 (#0)
*   Trying 52.202.51.185...
* Connected to updates.jenkins.io (52.202.51.185) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
* Server certificate:
*       subject: CN=updates.jenkins.io
*       start date: Aug 21 21:05:46 2020 GMT
*       expire date: Nov 19 21:05:46 2020 GMT
*       common name: updates.jenkins.io
*       issuer: CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US
> GET /download/plugins/branch-api/2.6.0/branch-api.hpi HTTP/1.1
> User-Agent: curl/7.29.0
> Host: updates.jenkins.io
> Accept: */*
> 
< HTTP/1.1 302 Found
< Date: Tue, 01 Sep 2020 23:42:14 GMT
< Server: Apache/2.4.29 (Ubuntu)
< Location: https://get.jenkins.io/plugins/branch-api/2.6.0/branch-api.hpi
< Content-Length: 246
< Content-Type: text/html; charset=iso-8859-1
< 
* Ignoring the response-body
{ [data not shown]
100   246  100   246    0     0    792      0 --:--:-- --:--:-- --:--:--   790
* Connection #0 to host updates.jenkins.io left intact
* Issue another request to this URL: 'https://get.jenkins.io/plugins/branch-api/2.6.0/branch-api.hpi'
* About to connect() to get.jenkins.io port 443 (#1)
*   Trying 52.167.253.43...
* Connected to get.jenkins.io (52.167.253.43) port 443 (#1)
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
*       subject: CN=get.jenkins.io
*       start date: Aug 23 06:03:38 2020 GMT
*       expire date: Nov 21 06:03:38 2020 GMT
*       common name: get.jenkins.io
*       issuer: CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US
> GET /plugins/branch-api/2.6.0/branch-api.hpi HTTP/1.1
> User-Agent: curl/7.29.0
> Host: get.jenkins.io
> Accept: */*
> 
< HTTP/1.1 302 Found
< Server: nginx/1.19.1
< Date: Tue, 01 Sep 2020 23:42:14 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 0
< Connection: keep-alive
< Cache-Control: private, no-cache
< Link: <https://mirror.xmission.com/jenkins/plugins/branch-api/2.6.0/branch-api.hpi>; rel=duplicate; pri=1; geo=us
< Location: https://ftp-chi.osuosl.org/pub/jenkins/plugins/branch-api/2.6.0/branch-api.hpi
< Strict-Transport-Security: max-age=15724800; includeSubDomains
< 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Connection #1 to host get.jenkins.io left intact
* Issue another request to this URL: 'https://ftp-chi.osuosl.org/pub/jenkins/plugins/branch-api/2.6.0/branch-api.hpi'
* About to connect() to ftp-chi.osuosl.org port 443 (#2)
*   Trying 64.50.236.52...
* Connected to ftp-chi.osuosl.org (64.50.236.52) port 443 (#2)
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
*       subject: CN=*.osuosl.org,OU=CASS,O=Oregon State University,STREET=121 Valley Library,L=Corvallis,ST=Oregon,postalCode=97331,C=US
*       start date: Jul 24 00:00:00 2020 GMT
*       expire date: Jul 24 23:59:59 2022 GMT
*       common name: *.osuosl.org
*       issuer: CN=InCommon RSA Server CA,OU=InCommon,O=Internet2,L=Ann Arbor,ST=MI,C=US
> GET /pub/jenkins/plugins/branch-api/2.6.0/branch-api.hpi HTTP/1.1
> User-Agent: curl/7.29.0
> Host: ftp-chi.osuosl.org
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Tue, 01 Sep 2020 23:42:14 GMT
< Server: Apache
< Last-Modified: Tue, 01 Sep 2020 00:16:41 GMT
< ETag: "4bdfe-5ae356ef1c964"
< Accept-Ranges: bytes
< Content-Length: 310782
< Content-Type: application/vnd.hp-hpid
< 
{ [data not shown]
100  303k  100  303k    0     0   424k      0 --:--:-- --:--:-- --:--:--  424k
* Connection #2 to host ftp-chi.osuosl.org left intact
```

**Comment by martinda** [comment]
I further modified the code to reveal the actual exception:
```
org.apache.http.conn.HttpHostConnectException: Connect to mirrors.tuna.tsinghua.edu.cn:443 [mirrors.tuna.tsinghua.edu.cn/101.6.8.193] failed: Connection timed out (Connection timed out)
Connect to mirrors.tuna.tsinghua.edu.cn:443 [mirrors.tuna.tsinghua.edu.cn/101.6.8.193] failed: Connection timed out (Connection timed out)
org.apache.http.conn.HttpHostConnectException: Connect to mirrors.tuna.tsinghua.edu.cn:443 [mirrors.tuna.tsinghua.edu.cn/101.6.8.193] failed: Connection timed out (Connection timed out)
    at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
    at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
    at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
    at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
    at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)                                                                                                                                                     at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)                                                                                                                                                      at io.jenkins.tools.pluginmanager.impl.PluginManager.downloadToFile(PluginManager.java:994)
    at io.jenkins.tools.pluginmanager.impl.PluginManager.downloadToFile(PluginManager.java:954)
    at io.jenkins.tools.pluginmanager.impl.PluginManager.downloadPlugin(PluginManager.java:884)
    at io.jenkins.tools.pluginmanager.impl.PluginManager.lambda$null$6(PluginManager.java:448)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
    at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)                                                                                                                                                                     at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)                                                                                                                                                                           at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)                                                                                                                                                                         at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)                                                                                                                                                                           at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)                                                                                                                                                               at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)                                                                                                                                                         at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)                                                                                                                                                                     at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
    at io.jenkins.tools.pluginmanager.impl.PluginManager.lambda$downloadPlugins$7(PluginManager.java:447)
    at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:589)
    at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:368)
    at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
    ... 31 more
location is null
Unable to download plugin git from https://updates.jenkins.io/download/plugins/git/4.4.0/git.hpi
```

**Comment by martinda** [comment]
After much debugging, the timeout occurs in the resource of this [try-with-resources](https://github.com/jenkinsci/plugin-installation-manager-tool/blob/master/plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/PluginManager.java#L988-L990) code block on one of the servers, and this fails the application without trying other servers.

**Comment by martinda** [comment]
There is a conversation on the [infra mailing list](https://groups.google.com/g/jenkins-infra/c/EZhBdCTMuQo) about this issue.

**Comment by timja** [comment]
Fixed in https://github.com/jenkins-infra/charts/pull/487
