### ISSUE TITLE
Allow downloading plugin via FTP

### ISSUE THREAD

**Issue by janisliepins** [jenkinsci/plugin-installation-manager-tool#196]
It is not possible to download .hpi file if it is on FTP server.

In plugins.txt:
...
my_plugin::ftp://example.com/jenkins_plugins/my_pluing.hpi
...

Error: Not able to resolve URL for plugin

**Comment by timja** [comment]
can you run it with verbose and attach the full error please?

**Comment by janisliepins** [comment]
`Will use url: ftp://example.com/ext/jenkins/plugins/basic-branch-build-strategies.hpi to download basic-branch-build-strategies plugin`
`Downloading plugin basic-branch-build-strategies from url: ftp://example.com/ext/jenkins/plugins/basic-branch-build-strategies.hpi`
`Unable to resolve plugin URL ftp://example.com/ext/jenkins/plugins/basic-branch-build-strategies.hpi, or download plugin basic-branch-build-strategies to file`
`io.jenkins.tools.pluginmanager.impl.DownloadPluginException: Unable to download basic-branch-build-strategies
        at io.jenkins.tools.pluginmanager.impl.PluginManager.lambda$null$6(PluginManager.java:454)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Unable to download basic-branch-build-strategies`

**Comment by janisliepins** [comment]
If we use http or https protocol - download from simple WEB server host - it works ok

**Comment by janisliepins** [comment]
@timja Please let me know if full replication is needed - im not able to share working FTP link currently but i could quickly setup one with plugin in it so it would be possible to fully replicate this error.

**Comment by timja** [comment]
that's fine, can you workaround it by using http / https? or can you not use the tool without ftp?

**Comment by janisliepins** [comment]
Currently as a workaround we have moved plugins to a web server. Since we are storing our plugins on FTP server it would be great to have implementation for downloading plugins from FTP also.

**Comment by jetersen** [comment]
In my opinion, FTP is out of scope. The protocol is not safe.

**Comment by janisliepins** [comment]
Closing this issue. We will start using HTTP/s protocol for plugin storage.
