### ISSUE TITLE
jenkins-update-center parameter does not take complete URL

### ISSUE THREAD

**Issue by jonbrohauge** [jenkinsci/plugin-installation-manager-tool#236]
Trying to use this tool in stead of the old shell script, however I find it strange that it does not take the complete customized URLs.

I'm executing this in my Dockerfile: 
```
JENKINS_UC=$ARTIFACTORY_URL/jenkins-update-remote
...
jenkins-plugin-cli --plugin-file /usr/share/jenkins/ref/plugins.txt --jenkins-update-center https://artifactory.domain.local/artifactory/jenkins-update-remote/update-center.json --verbose
```
Using JENKINS_UC works in the old shell script, however it looks like it is completely ignored, and thus the need for a "manullay" inserted URL for `--jenkins-update-center`.

As for experimental and incremental, I have no use for them. All my plugins in plugins.txt are versioned, i.e.
```
# Active Directory Plugin
active-directory:2.20

# Amazon Elastic Container Service Plugin
amazon-ecs:1.37

# Anchore Container Image Scanner Plugin
anchore-container-scanner:1.0.22

# Amazon Web Services SDK Plugin
aws-java-sdk:1.11.854

...
```

And the verbose output starts like this, which look fine to me:
```
File containing list of plugins to be downloaded: /usr/share/jenkins/ref/plugins.txt
Reading in plugins from /usr/share/jenkins/ref/plugins.txt

No directory to download plugins entered. Will use default of /usr/share/jenkins/ref/plugins
Using update center https://artifactory.domain.local/artifactory/jenkins-update-remote/update-center.json specified with CLI option
Using experimental update center https://updates.jenkins.io/experimental/update-center.json from JENKINS_UC_EXPERIMENTAL environment variable
Using incrementals mirror https://repo.jenkins-ci.org/incrementals from JENKINS_INCREMENTALS_REPO_MIRROR environment variable
No CLI option or environment variable set for plugin info, using default of https://updates.jenkins.io/plugin-versions.json
No war entered. Will use default of /usr/share/jenkins/jenkins.war
Jenkins version: 2.268

Retrieving update center information
Created cache at: /root/.cache/jenkins-plugin-management-cli
Cache miss for: update-center-2.268
Cache miss for: experimental-update-center-2.268
Cache miss for: plugin-versions
```

Then the actual output is (partial output only):
```
Downloading plugin pipeline-milestone-step from url: https://artifactory.domain.local/download/plugins/pipeline-milestone-step/1.3.1/pipeline-milestone-step.hpi
Unable to resolve plugin URL https://artifactory.domain.local/download/plugins/resource-disposer/0.14/resource-disposer.hpi, or download plugin resource-disposer to file
Will use url: https://artifactory.domain.local/download/plugins/job-dsl/1.77/job-dsl.hpi to download job-dsl plugin

Downloading plugin job-dsl from url: https://artifactory.domain.local/download/plugins/job-dsl/1.77/job-dsl.hpi
Unable to resolve plugin URL https://artifactory.domain.local/download/plugins/jacoco/3.1.0/jacoco.hpi, or download plugin jacoco to file
Will use url: https://artifactory.domain.local/download/plugins/authorize-project/1.3.0/authorize-project.hpi to download authorize-project plugin

Downloading plugin authorize-project from url: https://artifactory.domain.local/download/plugins/authorize-project/1.3.0/authorize-project.hpi
io.jenkins.tools.pluginmanager.impl.DownloadPluginException: Unable to download workflow-scm-step
        at io.jenkins.tools.pluginmanager.impl.PluginManager.lambda$null$5(PluginManager.java:457)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Unable to download workflow-scm-step
Unable to resolve plugin URL https://artifactory.domain.local/download/plugins/workflow-multibranch/2.22/workflow-multibranch.hpi, or download plugin workflow-multibranch to file
Will use url: https://artifactory.domain.local/download/plugins/active-directory/2.20/active-directory.hpi to download active-directory plugin

Downloading plugin active-directory from url: https://artifactory.domain.local/download/plugins/active-directory/2.20/active-directory.hpi
Unable to resolve plugin URL https://artifactory.domain.local/download/plugins/blueocean-rest-impl/1.24.3/blueocean-rest-impl.hpi, or download plugin blueocean-rest-impl to file
Will use url: https://artifactory.domain.local/download/plugins/run-condition/1.3/run-condition.hpi to download run-condition plugin
```

**Comment by timja** [comment]
JENKINS_UC should be set here: https://github.com/jenkinsci/plugin-installation-manager-tool/blob/fdf0ee840ca28c00811197f5ed9eda052f216f5f/plugin-management-cli/src/main/java/io/jenkins/tools/pluginmanager/cli/CliOptions.java#L310

**Comment by jonbrohauge** [comment]
I might have been blinded by the fact that the URL in the output, appears to be shortened. Why I cannot figure out.

**Comment by jonbrohauge** [comment]
Apparently upgrading to 2.269 to get the almost latest version, and the discovery of JENKINS_UC_DOWNLOAD helped.
