### ISSUE TITLE
Unable to resolve url/Downloaded file is not a valid ZIP

### ISSUE THREAD

**Issue by alexhopeoconnor** [jenkinsci/plugin-installation-manager-tool#281]
Getting errors trying to run the basic usage example of the tool, not sure if I am doing anything wrong but I have downloaded latest stable jenkins.war

Here is the commands I have tried running and their output:
`java -jar 'C:\jenkins-plugin-manager.jar' --war 'C:\jenkins.war' -p git`

Output:
```
Picked up _JAVA_OPTIONS: -Djenkins.install.runSetupWizard=false
Downloaded file is not a valid ZIP
Downloaded file is not a valid ZIP
Downloaded file is not a valid ZIP
Downloaded file is not a valid ZIP
Downloaded file is not a valid ZIP
Unable to download mailer
```

Also:
`java -jar 'C:\jenkins-plugin-manager.jar' --war 'C:\jenkins.war' -p git --verbose`

Output:
```
Picked up _JAVA_OPTIONS: -Djenkins.install.runSetupWizard=false
No .txt or .yaml file containing list of plugins to be downloaded entered.
No directory to download plugins entered. Will use default of C:\ProgramData\Jenkins\Reference\Plugins
No CLI option or environment variable set for update center, using default of https://updates.jenkins.io/update-center.json
No CLI option or environment variable set for experimental update center, using default of https://updates.jenkins.io/experimental/update-center.json
No CLI option or environment variable set for incrementals mirror, using default of https://repo.jenkins-ci.org/incrementals
No CLI option or environment variable set for plugin info, using default of https://updates.jenkins.io/plugin-versions.json
Will use war file: C:\jenkins.war
Jenkins version: 2.263.3

Retrieving update center information
Returning cached value for: update-center-2.263.3
Returning cached value for: experimental-update-center-2.263.3
Returning cached value for: plugin-versions
Couldn't find checksum for git at version: latest

git depends on:
workflow-scm-step 2.11
workflow-step-api 2.23
credentials 2.3.14
git-client 3.6.0
mailer 1.32.1
scm-api 2.6.4
script-security 1.76
ssh-credentials 1.18.1
structs 1.20
Setting checksum for: workflow-scm-step to fgtY8ip1eck38wgcZ8JJ1OrWeOAalUR4/dWbDL46iXw=

workflow-scm-step depends on:
workflow-step-api 2.23
Setting checksum for: workflow-step-api to 4OOcvgw+v7LT+A7f70cNPH0DPH3q+sjG5VPn05HqEoc=

workflow-step-api depends on:
structs 1.20
Setting checksum for: credentials to Yt1SWoBFW27T6u0cUdesZUYYMEI29DhA048HlOge3RI=

credentials depends on:
structs 1.20
Setting checksum for: git-client to YSF0mAiiNfxKEvSlvZfLYcAKnSq3xcSS8YJS+Jfdxxk=

git-client depends on:
apache-httpcomponents-client-4-api 4.5.13-1.0
credentials 2.3.14
jsch 0.1.55.2
script-security 1.76
ssh-credentials 1.18.1
structs 1.20
trilead-api 1.0.13
Setting checksum for: mailer to CwReqH78KJ/MrVWsUeTJA5RdloO3G0hmfhlEDkKi02g=

mailer depends on:
display-url-api 2.3.4
Setting checksum for: scm-api to k1y65LRmeNWt+fqsmmgCn1KgTg0MickDinq5XKa2dtw=

scm-api depends on:
structs 1.20
Setting checksum for: script-security to ivbfliUh95tjbeY6JCacEVM5G7caoJsGuVA5VHcTi4I=

script-security has no dependencies
Setting checksum for: ssh-credentials to jbkIxIRzfyYM+rZoKkLL6vOQs7nv2HklN1aR5Fw3BJI=

ssh-credentials depends on:
credentials 2.3.14
trilead-api 1.0.13
Setting checksum for: structs to fnhhNWo3qmpydGLXrqcW3ZMHBxJS9zScJybWSnc/6zo=

structs has no dependencies
Setting checksum for: apache-httpcomponents-client-4-api to H6Wtr80EPFgqm27ESmo3Fm23e7bVt9LE+ZAq0mOmVjY=

apache-httpcomponents-client-4-api has no dependencies
Setting checksum for: jsch to zcdL+OQ+tArmrZi6L4ZsiJFAgDhpnam4NlGKHYkj/EQ=

jsch depends on:
ssh-credentials 1.18.1
trilead-api 1.0.13
Setting checksum for: trilead-api to YrRoOOSTz8aVA4K05JddhlzTv7/FitpwS53Zb/EB5Fc=

trilead-api has no dependencies
Setting checksum for: display-url-api to 1JoJw0ZFVBj0XrNNiD48gsoA1/pYzc4aRSIk4DJAHkE=

display-url-api has no dependencies
Setting checksum for: git to gzQ5AL2IPgeiJP4eOYw01IHrjk2cP5GG2FsQfQB7ZSg=
Setting checksum for: git to gzQ5AL2IPgeiJP4eOYw01IHrjk2cP5GG2FsQfQB7ZSg=
Setting checksum for: git to gzQ5AL2IPgeiJP4eOYw01IHrjk2cP5GG2FsQfQB7ZSg=
Setting checksum for: git to gzQ5AL2IPgeiJP4eOYw01IHrjk2cP5GG2FsQfQB7ZSg=
Setting checksum for: git to gzQ5AL2IPgeiJP4eOYw01IHrjk2cP5GG2FsQfQB7ZSg=
Setting checksum for: git to gzQ5AL2IPgeiJP4eOYw01IHrjk2cP5GG2FsQfQB7ZSg=
Setting checksum for: git to gzQ5AL2IPgeiJP4eOYw01IHrjk2cP5GG2FsQfQB7ZSg=
Setting checksum for: git to gzQ5AL2IPgeiJP4eOYw01IHrjk2cP5GG2FsQfQB7ZSg=
Setting checksum for: git to gzQ5AL2IPgeiJP4eOYw01IHrjk2cP5GG2FsQfQB7ZSg=
Setting checksum for: git to gzQ5AL2IPgeiJP4eOYw01IHrjk2cP5GG2FsQfQB7ZSg=
Setting checksum for: git to gzQ5AL2IPgeiJP4eOYw01IHrjk2cP5GG2FsQfQB7ZSg=
Setting checksum for: git to gzQ5AL2IPgeiJP4eOYw01IHrjk2cP5GG2FsQfQB7ZSg=
Setting checksum for: git to gzQ5AL2IPgeiJP4eOYw01IHrjk2cP5GG2FsQfQB7ZSg=
Setting checksum for: git to gzQ5AL2IPgeiJP4eOYw01IHrjk2cP5GG2FsQfQB7ZSg=
Will install new plugin credentials 2.3.14
Will install new plugin workflow-step-api 2.23
Will install new plugin mailer 1.32.1
Will install new plugin trilead-api 1.0.13
Will install new plugin git 4.5.2
Will install new plugin script-security 1.76
Will install new plugin jsch 0.1.55.2
Will use url: https://updates.jenkins.io/download/plugins/git/4.5.2/git.hpi to download git plugin
Will use url: https://updates.jenkins.io/download/plugins/workflow-step-api/2.23/workflow-step-api.hpi to download workflow-step-api plugin
Will use url: https://updates.jenkins.io/download/plugins/credentials/2.3.14/credentials.hpi to download credentials plugin
Will use url: https://updates.jenkins.io/download/plugins/trilead-api/1.0.13/trilead-api.hpi to download trilead-api plugin
Will use url: https://updates.jenkins.io/download/plugins/script-security/1.76/script-security.hpi to download script-security plugin
Will use url: https://updates.jenkins.io/download/plugins/jsch/0.1.55.2/jsch.hpi to download jsch plugin
Will use url: https://updates.jenkins.io/download/plugins/mailer/1.32.1/mailer.hpi to download mailer plugin
Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/jsch/0.1.55.2/jsch.hpi, or download plugin jsch to file
Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/credentials/2.3.14/credentials.hpi, or download plugin credentials to file
Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/mailer/1.32.1/mailer.hpi, or download plugin mailer to file
Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/git/4.5.2/git.hpi, or download plugin git to file
Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/trilead-api/1.0.13/trilead-api.hpi, or download plugin trilead-api to file
Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/script-security/1.76/script-security.hpi, or download plugin script-security to file
Checksum valid for: workflow-step-api
Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/mailer/1.32.1/mailer.hpi, or download plugin mailer to file
Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/git/4.5.2/git.hpi, or download plugin git to file
Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/trilead-api/1.0.13/trilead-api.hpi, or download plugin trilead-api to file
Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/jsch/0.1.55.2/jsch.hpi, or download plugin jsch to file
Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/script-security/1.76/script-security.hpi, or download plugin script-security to file
Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/git/4.5.2/git.hpi, or download plugin git to file
Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/jsch/0.1.55.2/jsch.hpi, or download plugin jsch to file
Downloaded file is not a valid ZIP
Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/mailer/1.32.1/mailer.hpi, or download plugin mailer to file
java.nio.file.NoSuchFileException: C:\Users\alexh\AppData\Local\Temp\plugin-installation-manager-downloads918782679408011570\git.jpiDownloaded file is not a valid ZIP

Downloaded file is not a valid ZIP
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:194)
        at java.base/java.nio.file.Files.readAttributes(Files.java:1763)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1222)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:726)
        at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:843)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:246)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:176)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:346)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:317)Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/trilead-api/1.0.13/trilead-api.hpi, or download plugin trilead-api to file

        at java.base/java.util.jar.JarFile.<init>(JarFile.java:283)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.downloadToFile(PluginManager.java:1141)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.downloadToFile(PluginManager.java:1069)
Downloaded file is not a valid ZIP
        at io.jenkins.tools.pluginmanager.impl.PluginManager.downloadPlugin(PluginManager.java:998)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.lambda$null$5(PluginManager.java:488)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)
        at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:661)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.lambda$downloadPlugins$6(PluginManager.java:487)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
java.nio.file.NoSuchFileException: C:\Users\alexh\AppData\Local\Temp\plugin-installation-manager-downloads918782679408011570\trilead-api.jpi
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:194)
        at java.base/java.nio.file.Files.readAttributes(Files.java:1763)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1222)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:726)
        at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:843)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:246)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:176)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:346)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:317)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:283)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.downloadToFile(PluginManager.java:1141)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.downloadToFile(PluginManager.java:1069)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.downloadPlugin(PluginManager.java:998)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.lambda$null$5(PluginManager.java:488)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
java.nio.file.NoSuchFileException: C:\Users\alexh\AppData\Local\Temp\plugin-installation-manager-downloads918782679408011570\mailer.jpi
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:194)
        at java.base/java.nio.file.Files.readAttributes(Files.java:1763)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1222)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:726)
        at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:843)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:246)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:176)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:346)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:317)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:283)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.downloadToFile(PluginManager.java:1141)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.downloadToFile(PluginManager.java:1069)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.downloadPlugin(PluginManager.java:998)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.lambda$null$5(PluginManager.java:488)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
java.nio.file.NoSuchFileException: C:\Users\alexh\AppData\Local\Temp\plugin-installation-manager-downloads918782679408011570\jsch.jpi
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:194)
        at java.base/java.nio.file.Files.readAttributes(Files.java:1763)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1222)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:726)
        at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:843)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:246)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:176)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:346)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:317)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:283)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.downloadToFile(PluginManager.java:1141)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.downloadToFile(PluginManager.java:1069)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.downloadPlugin(PluginManager.java:998)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.lambda$null$5(PluginManager.java:488)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
io.jenkins.tools.pluginmanager.impl.DownloadPluginException: Unable to download git
        at io.jenkins.tools.pluginmanager.impl.PluginManager.lambda$null$5(PluginManager.java:493)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)
        at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:661)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.lambda$downloadPlugins$6(PluginManager.java:487)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Unable to download git
```

I also tried pinning the plugin version, but same result:
`java -jar 'C:\jenkins-plugin-manager.jar' --war 'C:\jenkins.war' -p git:4.5.1`

Output:
Picked up _JAVA_OPTIONS: -Djenkins.install.runSetupWizard=false
Downloaded file is not a valid ZIP
Downloaded file is not a valid ZIP
Downloaded file is not a valid ZIP
Downloaded file is not a valid ZIP
Downloaded file is not a valid ZIP
Unable to download trilead-api

Looking through the verbose output it seems to be failing to resolve random URLs each time I run the command, I tried installing plugins in jenkins through the browser interface and it seems to work, so I don't think it is a particular issue with my network currently.

Is this an issue with the plugin manager? Are there any options I could try to maybe make it retry URLs a few times in case the jenkins update center in under heavy load or something?

**Comment by alexhopeoconnor** [comment]
Still not sure what is going on but looking at the PluginManager type: https://github.com/jenkinsci/plugin-installation-manager-tool/blob/26e468c5727594f1763da89fce4fe9274ad0630d/plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/PluginManager.java#L1120

It looks like the underlying exception is either URISyntaxException or IOException, the syntax or the URLs seems correct and pasting them into the browser results in a file being downloaded, but I need to try figuring out how to build the tool to debug any further.

**Comment by alexhopeoconnor** [comment]
So after debugging this a bit further I am getting the exception message:
`javax.net.ssl.SSLException: No PSK available. Unable to resume.`

I think it could be related to a bug in the JDK?
https://stackoverflow.com/questions/52574050/javax-net-ssl-sslexception-no-psk-available-unable-to-resume

**Comment by timja** [comment]
Are you behind a corporate firewall?

**Comment by alexhopeoconnor** [comment]
> Are you behind a corporate firewall?

No I am just on a normal connection to the net.

I fixed this by upgrading from openjdk 11 to 14, has something to do with SSL.
