### ISSUE TITLE
NPE in io.jenkins.tools.pluginmanager.impl.PluginManager.resolveDependenciesFromManifest

### ISSUE THREAD

**Issue by kwin** [jenkinsci/plugin-installation-manager-tool#301]
I have seen the following NPE while installing plugins with 2.8.0

```
java.lang.NullPointerException
		at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1770)
		at java.base/java.util.regex.Matcher.reset(Matcher.java:416)
		at java.base/java.util.regex.Matcher.<init>(Matcher.java:253)
		at java.base/java.util.regex.Pattern.matcher(Pattern.java:1133)
		at hudson.util.VersionNumber.parseVersion(VersionNumber.java:377)
		at hudson.util.VersionNumber.<init>(VersionNumber.java:368)
		at io.jenkins.tools.pluginmanager.impl.Plugin.setJenkinsVersion(Plugin.java:68)
		at io.jenkins.tools.pluginmanager.impl.PluginManager.resolveDependenciesFromManifest(PluginManager.java:883)
		at io.jenkins.tools.pluginmanager.impl.PluginManager.resolveDirectDependencies(PluginManager.java:1003)
		at io.jenkins.tools.pluginmanager.impl.PluginManager.resolveRecursiveDependencies(PluginManager.java:1037)
		at io.jenkins.tools.pluginmanager.impl.PluginManager.findPluginsAndDependencies(PluginManager.java:624)
		at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:189)
```

**Comment by kwin** [comment]
This seems to be triggered if the manifest file of the plugin does not contain attribute `Jenkins-Version`.

You can reproduce via
```java -jar plugin-management-cli/target/jenkins-plugin-manager-2.7.x-SNAPSHOT.jar --plugins nabaztag:1.9 -d plugins/ --war ~/Downloads/jenkins.war --verbose```

The hpi at https://updates.jenkins.io/download/plugins/nabaztag/1.9/nabaztag.hpi contains a MANIFEST which looks like this

```
Manifest-Version: 1.0
Archiver-Version: Plexus Archiver
Created-By: Apache Maven
Built-By: ericlemerdy
Build-Jdk: 1.6.0_0
Extension-Name: nabaztag
Implementation-Title: nabaztag
Implementation-Version: 1.9
Short-Name: nabaztag
Long-Name: nabaztag
Url: http://wiki.hudson-ci.org/display/HUDSON/Nabaztag+Plugin
Plugin-Version: 1.9
Hudson-Version: 1.352
Plugin-Developers: Stephan Noske:stephannoske:,Eric Le Merdy:ericlemer
 dy:
```

Instead of `Jenkins-Version` it has the attribute `Hudson-Version`. Should that be supported as well?

**Comment by kwin** [comment]
Another example can be found at https://updates.jenkins.io/download/plugins/ruby/1.2/ruby.hpi

**Comment by timja** [comment]
Both of those plugins appear to be removed from distribution, so no I don't think so.

**Comment by kwin** [comment]
Ok, I will come up with a patch which throws a proper exception in that case (saying "this is a non-supported hudson plugin")

**Comment by oleg-nenashev** [comment]
Adding support for `Hudson-Version` is trivial, so why not? As long as
nobody tries to use Hudson 3 plugins (not avail in the Jenkins update
center), it should be fine as a fallback option

**Comment by kwin** [comment]
@oleg-nenashev Which version number of Hudson matches which version number of Jenkins?

**Comment by oleg-nenashev** [comment]
Hudson was renamed to Jenkins in 1.396.
Hudson 1...1.395, then Jenkins 1.396+
