### ISSUE TITLE
Improve resilience against broken mirrors

### ISSUE THREAD

**Issue by kwin** [jenkinsci/plugin-installation-manager-tool#341]
Recently mirror.serverion.com returned empty responses for certain plugins e.g.

```
curl -v https://mirror.serverion.com/jenkins/plugins/disk-usage/0.28/disk-usage.hpi
*   Trying 185.28.39.100...
* TCP_NODELAY set
* Connected to mirror.serverion.com (185.28.39.100) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=mirror.serverion.com
*  start date: May  6 16:38:13 2021 GMT
*  expire date: Aug  4 16:38:13 2021 GMT
*  subjectAltName: host "mirror.serverion.com" matched cert's "mirror.serverion.com"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
> GET /jenkins/plugins/disk-usage/0.28/disk-usage.hpi HTTP/1.1
> Host: mirror.serverion.com
> User-Agent: curl/7.64.1
> Accept: */*
>
* Empty reply from server
* Connection #0 to host mirror.serverion.com left intact
curl: (52) Empty reply from server
* Closing connection 0
```

That leads to the following error in the jenkins-plugin-cli (v.2.9.3)

```
#17 56.47 Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/disk-usage/0.28/disk-usage.hpi, or download plugin disk-usage to file
#17 56.47 Tried downloading disk-usage from https://mirror.serverion.com/jenkins/plugins/disk-usage/0.28/disk-usage.hpi
#17 56.47 Downloaded file is not a valid ZIP
#17 56.47 java.nio.file.NoSuchFileException: /tmp/plugin-installation-manager-downloads867082607961164703/disk-usage.jpi
#17 56.47 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
#17 56.47 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
#17 56.47 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
#17 56.47 	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
#17 56.47 	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
#17 56.47 	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
#17 56.47 	at java.base/java.nio.file.Files.readAttributes(Files.java:1764)
#17 56.47 	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1239)
#17 56.47 	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:732)
#17 56.47 	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:849)
#17 56.47 	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:247)
#17 56.47 	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
#17 56.47 	at java.base/java.util.jar.JarFile.<init>(JarFile.java:348)
#17 56.47 	at java.base/java.util.jar.JarFile.<init>(JarFile.java:319)
#17 56.47 	at java.base/java.util.jar.JarFile.<init>(JarFile.java:285)
#17 56.47 	at io.jenkins.tools.pluginmanager.impl.PluginManager.downloadToFile(PluginManager.java:1293)
#17 56.47 	at io.jenkins.tools.pluginmanager.impl.PluginManager.downloadToFile(PluginManager.java:1215)
#17 56.47 	at io.jenkins.tools.pluginmanager.impl.PluginManager.downloadPlugin(PluginManager.java:1144)
#17 56.47 	at io.jenkins.tools.pluginmanager.impl.PluginManager.lambda$downloadPlugins$4(PluginManager.java:554)
#17 56.47 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
#17 56.47 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
#17 56.47 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
#17 56.47 	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
#17 56.47 	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
#17 56.47 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
#17 56.47 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
#17 56.47 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
#17 56.47 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
#17 56.47 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

Would be nice to transparently fallback to another mirror in that case instead of failing.

**Comment by kwin** [comment]
Also the underlying IOException in https://github.com/jenkinsci/plugin-installation-manager-tool/blob/105bda8665d45e245fd5335c5bfe4d535caab05e/plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/PluginManager.java#L1259 should be properly logged.

**Comment by kwin** [comment]
Would it be acceptable to fall back to http://mirrors.jenkins-ci.org/plugins/ in case mirror downloads fail 3 times?

**Comment by timja** [comment]
https://archives.jenkins.io/ is the official fallback mirror, @olblak would it be ok to hardcode a fallback after the mirror that get.jenkins.io gives out fails 3 times?

**Comment by kwin** [comment]
Is there any other API which allows to retrieve possible mirror URLs? Then we can also try out other mirrors before falling back to archives.jenkins-ci.org...

**Comment by timja** [comment]
This shows the mirrors, I'm not sure if there's an API, it uses something called `mirrorbits`

**Comment by olblak** [comment]
Unfortunately, I can't really think of a good solution here as we still have optimization to do on the mirror infrastructure.

The most up-to-date mirrors are "ftp-nyc.osuosl.org" and "ftp-chi.osuosl.org" but they remove content older than one year old.
archives.jenkins-ci.org is the only mirror at the moment that contains every older file but it can take several hours before the moment a new plugin version is published and gets propagated to archives.jenkins-ci.org.
Also, archives.jenkins-ci.org is limited in terms of network bandwidth so if you redirect every request to that service then you create a big bottleneck. That's what happened over the past months when we were using that service as a fallback solution.

@kwin mirrors.jenkins-ci.org is kept for backward compatibility but it's an old service that has many limitations such as no HTTPS support. it uses a different(mirrorbrain) engine than mirrors.jenkins.io (mirrorbits).

if we want to use archives as a fallback and be immediately up to date, we must trigger its updated from here https://github.com/jenkins-infra/mirror-scripts/blob/9b4d4c688e9efb9b056c13292b51b4fb0d09744e/sync-recent-releases.sh#L40
