### ISSUE TITLE
Unable to basic auth using credentials option

### ISSUE THREAD

**Issue by symlinx** [jenkinsci/plugin-installation-manager-tool#347]
Hi, 

### Version report

Jenkins and plugins versions report:

```
Jenkins version: 2.289.2-cb-3

& cat plugins.yaml 
plugins:
  - artifactId: git
    source:
      version: latest
```

I use the managed master docker image cloudbees/cloudbees-core-mm:2.289.2.2
In a container of the image :

```
$ uname -a
Linux 69d0e0fd597f 5.10.25-linuxkit #1 SMP Tue Mar 23 09:27:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

$ java -version
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)
```

### Reproduction steps

I use jenkins-plugin-manager in a Dockerfile to install some plugins
We are proxifing Jenkins update center using Artifactory. Artifactory needs the requests to be identified with creds (basic auth user:password)

However I am unable to authenticate against Artifactory using the '--credentials' option

```
& export JENKINS_UC=https://repo.artifactory.lan/artifactory/cloudbees-update-center/update-center/cje-mm/update-center.json

& java -jar jenkins-plugin-manager-2.10.0.jar --plugin-file plugins.yaml  --verbose --credentials 'repo.artifactory.lan:username:password'

```

### Results

The jenkins-plugin-manager jar gets a 401 HTTP Error from the server :
```
& java -jar jenkins-plugin-manager-2.10.0.jar --plugin-file plugins.yaml  --verbose --credentials 'repo.artifactory.lan:username:password'
File containing list of plugins to be downloaded: plugins.yaml
Reading in plugins from plugins.yaml

No directory to download plugins entered. Will use default of /usr/share/jenkins/ref/plugins
Using update center https://repo.artifactory.lan/artifactory/cloudbees-update-center/update-center/cje-mm/update-center.json from JENKINS_UC environment variable
No CLI option or environment variable set for experimental update center, using default of https://updates.jenkins.io/experimental/update-center.json
No CLI option or environment variable set for incrementals mirror, using default of https://repo.jenkins-ci.org/incrementals
No CLI option or environment variable set for plugin info, using default of https://updates.jenkins.io/plugin-versions.json
No war entered. Will use default of /usr/share/jenkins/jenkins.war
Jenkins version: 2.289.2-cb-3

Retrieving update center information
Cache miss for: update-center-2.289.2-cb-3
io.jenkins.tools.pluginmanager.impl.UpdateCenterInfoRetrievalException: Error getting update center json
        at io.jenkins.tools.pluginmanager.impl.PluginManager.getJson(PluginManager.java:786)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.getUCJson(PluginManager.java:805)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:203)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:167)
        at io.jenkins.tools.pluginmanager.cli.Main.main(Main.java:70)
Caused by: java.io.IOException: Server returned HTTP response code: 401 for URL: https://repo.artifactory.lan/artifactory/cloudbees-update-center/update-center/cje-mm/update-center.json?version=2.289.2-cb-3
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
        at java.net.URL.openStream(URL.java:1068)
        at org.apache.commons.io.IOUtils.toString(IOUtils.java:2960)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.getJson(PluginManager.java:780)
        ... 4 more
Error getting update center json
```

Artifactory logs say that the request is not authenticated :
```
non_authenticated_user|GET|/cloudbees-update-center/update-center/cje-mm/update-center.json|401|-1|0|3|Java/1.8.0_292
```

Expected result:

I would expect that the jar retrieves the update-center.json file from Artifactory just like I get it using a curl command with the same creds

```
& curl -I -u username:password https://repo.artifactory.lan/artifactory/cloudbees-update-center/update-center/cje-mm/update-center.json?version=2.289.2-cb-3
HTTP/1.1 200 OK
Date: Fri, 09 Jul 2021 20:47:43 GMT
Content-Type: application/json
Content-Length: 1856377
Connection: keep-alive
Last-Modified: Fri, 09 Jul 2021 17:08:29 GMT
ETag: 498d57992f13c805a953f487a35ef5d59a2ab671
X-Checksum-Sha1: 498d57992f13c805a953f487a35ef5d59a2ab671
X-Checksum-Sha256: b0870486193cb151e20b20f033f1ea7c8480f1c8a55460f38a767810b6ad074a
X-Checksum-Md5: d1afee726cc7a04896eccddf9b9fc170
Accept-Ranges: bytes
X-Artifactory-Filename: update-center.json
Content-Disposition: attachment; filename="update-center.json"; filename*=UTF-8''update-center.json
```

Am I missing something (in the credentials option host format ? tried a lot of combinations) if so could you please provide me with an example (couldn't find it)... or is this a bug ?

Thank you for your help :)

**Comment by Vincevrp** [comment]
Can confirm. I'm experiencing the same issue.

**Comment by timja** [comment]
cc @kwin
