### ISSUE TITLE
Tool has no support for proxy servers

### ISSUE THREAD

**Issue by IONKnight** [jenkinsci/plugin-installation-manager-tool#74]
Currently the installation tool has no support for proxy servers. This would make a massive difference for adoption in larger corporate offices.

Posting snippets of the log first part repeats for each section
```Retrieving update center information

credentials depends on: 
structs 1.7

structs has no dependencies

blueocean depends on: 
blueocean-bitbucket-pipeline 1.21.0
blueocean-commons 1.21.0
blueocean-config 1.21.0
blueocean-core-js 1.21.0
blueocean-dashboard 1.21.0
blueocean-events 1.21.0
blueocean-git-pipeline 1.21.0
blueocean-github-pipeline 1.21.0
blueocean-i18n 1.21.0
blueocean-jira 1.21.0
blueocean-jwt 1.21.0
blueocean-personalization 1.21.0
blueocean-pipeline-api-impl 1.21.0
blueocean-pipeline-editor 1.21.0
blueocean-rest-impl 1.21.0
blueocean-rest 1.21.0
blueocean-web 1.21.0
jenkins-design-language 1.21.0
blueocean-autofavorite 1.2.3
blueocean-display-url 2.2.0
pipeline-build-step 2.7
pipeline-milestone-step 1.3.1
```
End Error
```
Resolving dependencies of scm-api by downloading plugin to temp file /tmp/scm-api5982136854335144858.jpi and parsing MANIFEST.MF
Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/scm-api/2.0.1-beta-1/scm-api.hpi, or download plugin scm-api to file
First download attempt of scm-api unsuccessful, reattempting
Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/scm-api-plugin/2.0.1-beta-1/scm-api-plugin.hpi, or download plugin scm-api-plugin to file
io.jenkins.tools.pluginmanager.impl.DownloadPluginException: Unable to resolve dependencies for scm-api-plugin
	at io.jenkins.tools.pluginmanager.impl.PluginManager.resolveDependenciesFromManifest(PluginManager.java:572)
	at io.jenkins.tools.pluginmanager.impl.PluginManager.resolveDirectDependencies(PluginManager.java:692)
	at io.jenkins.tools.pluginmanager.impl.PluginManager.resolveRecursiveDependencies(PluginManager.java:716)
	at io.jenkins.tools.pluginmanager.impl.PluginManager.findPluginsAndDependencies(PluginManager.java:436)
	at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:118)
	at io.jenkins.tools.pluginmanager.cli.Main.main(Main.java:37)
Unable to resolve dependencies for scm-api-plugin
ERROR: Service 'jenkins' failed to build: The command '/bin/sh -c java -Dhttp.proxyHost=xx.xx.xx.xx -Dhttp.proxyPort=8080 -Dhttps.proxyHost=xx.xx.xx.xx -Dhttps.proxyPort=8080 -jar jenkins-plugin-manager-1.0.1.jar -f /usr/share/jenkins/ref/jenkins-plugins.txt --verbose' returned a non-zero code: 1
```

**Comment by timja** [comment]
> Currently the installation tool has no support for proxy servers. This would make a massive difference for adoption in larger corporate offices.

shouldn't be much work to add it, we use the apache http client.
https://stackoverflow.com/a/36714450/4951015

This is easier to test for someone behind a corporate proxy, if someone wants to contribute it or offer to verify a fix

**Comment by IONKnight** [comment]
Happy to verify the fix
